id: P4264B2BD
initial_creation_type: input
source_metadata:
  title: Tarthang Tulku
  language: bo
  description: 'Texts by Tarthang Tulku Kunga Gelek Yeshe Dorje (dar thang sprul sku
    kun dga'' dge legs ye shes rdo rje, b. 1935):'
  volume:
    0ec902e1d63e454e9582015052e7d09c:
      title: Prayer to Khandro Tsering Chödrön
      parent: Prayers
created_at: '2022-03-01T01:39:48.534911'
last_modified_at: '2022-03-01T01:39:48.534914'
statistics:
  total_words: 133
  total_non_words: 10
quality:
  non_words_ratio: 0.08
